# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:   
  stats:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: manuelmartin-developer
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid
          
  achievements:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - uses: lowlighter/metrics@master
        with:
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: manuelmartin-developer
          template: classic
          base: ""
          config_display: large
          config_timezone: Europe/Madrid
          config_output: svg
          filename: achievements.svg
          repositories_batch: 5

          # Achievement plugin
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact 
